import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'

// ── Static data ─────────────────────────────────────────────────
const PLANS = [
  { id: 'pack', label: 'Policy Pack', price: '$299', period: 'one-time', desc: '7 AI governance documents generated by Claude AI, customised to your company', popular: true },
  { id: 'annual', label: 'Annual', price: '$199', period: '/ year', desc: 'Policy pack + annual refresh as standards evolve' },
]

const POLICY_DOCS = [
  { id: 'ai-governance',    name: 'AI Governance Policy',                   clause: 'ISO 42001 §4–6' },
  { id: 'risk-framework',   name: 'AI Risk Assessment Framework',            clause: 'ISO 42001 §6.1, 8.4' },
  { id: 'incident-response',name: 'AI Incident Response Plan',               clause: 'ISO 42001 §8.3, 10.1' },
  { id: 'transparency',     name: 'Transparency & Explainability Policy',    clause: 'ISO 42001 §8.5; EU AI Act Art.13' },
  { id: 'data-governance',  name: 'AI Data Governance Policy',              clause: 'ISO 42001 §8.2, 8.6; GDPR Art.35' },
  { id: 'vendor-policy',    name: 'Third-Party AI Vendor Policy',           clause: 'ISO 42001 §8.7; GDPR Art.28' },
  { id: 'readiness-report', name: 'ISO 42001 Readiness Report',             clause: 'ISO 42001 — Full Standard' },
]

const JURISDICTION_OPTIONS = ['European Union', 'United Kingdom', 'United States', 'Canada', 'Australia', 'Singapore', 'UAE', 'Other']
const REVIEWER_OPTIONS      = ['Series A / B investors', 'Enterprise customers (procurement)', 'ISO 42001 auditor', 'Regulatory authority', 'Board / Legal counsel', 'Cyber insurance underwriter']
const TIMELINE_OPTIONS      = [
  { value: 'urgent',  label: 'Urgent — within 30 days',     sub: 'Active due diligence / customer requirement' },
  { value: 'normal',  label: 'Normal — 1 to 3 months',      sub: 'Upcoming fundraise or procurement process' },
  { value: 'planning',label: 'Planning — 3 to 6 months',    sub: 'Building governance ahead of growth' },
]
const PERSONAL_DATA_OPTIONS = [
  { value: 'yes',  label: 'Yes — we process personal data in our AI systems' },
  { value: 'some', label: 'Some — depends on the use case' },
  { value: 'no',   label: 'No — our AI only processes non-personal data' },
]

// Context wizard questions
const QUESTIONS = [
  {
    id: 'aiDescription',
    label: 'What does your AI actually do?',
    sub: 'Describe what your AI system(s) do for customers. Be specific — this shapes every policy.',
    type: 'textarea',
    placeholder: 'e.g. We use GPT-4 to analyse customer support tickets and auto-suggest responses. We also use a custom ML model to flag fraudulent transactions in real-time.',
    required: true,
  },
  {
    id: 'aiModels',
    label: 'What AI models or services do you use?',
    sub: 'List the specific models and providers. This determines your vendor policy obligations.',
    type: 'textarea',
    placeholder: 'e.g. OpenAI GPT-4o via API, Anthropic Claude for internal tooling, custom scikit-learn model for churn prediction hosted on AWS SageMaker.',
    required: true,
  },
  {
    id: 'jurisdictions',
    label: 'Which markets does your AI operate in?',
    sub: 'Select all jurisdictions where your AI systems are used or where data is processed.',
    type: 'multiselect',
    options: JURISDICTION_OPTIONS,
    required: true,
  },
  {
    id: 'personalData',
    label: 'Do your AI systems process personal data?',
    sub: 'This determines GDPR Art. 35 DPIA obligations and data governance requirements.',
    type: 'singleselect',
    options: PERSONAL_DATA_OPTIONS,
    required: true,
  },
  {
    id: 'reviewers',
    label: 'Who will review these policies?',
    sub: 'Select all that apply — this calibrates the technical depth and legal precision of each document.',
    type: 'multiselect',
    options: REVIEWER_OPTIONS,
    required: true,
  },
  {
    id: 'timeline',
    label: 'What is driving this and what is your timeline?',
    sub: 'This determines how we prioritise and frame the remediation roadmap.',
    type: 'singleselect',
    options: TIMELINE_OPTIONS,
    required: true,
  },
  {
    id: 'existingDocs',
    label: 'Do you have any existing AI or data governance documentation?',
    sub: 'Even partial documentation matters — it changes what the policies need to establish vs. supplement.',
    type: 'yesno',
    required: true,
  },
  {
    id: 'existingDocsDesc',
    label: 'Describe your existing documentation',
    sub: 'What do you have? Even rough notes or slide decks count.',
    type: 'textarea',
    placeholder: 'e.g. We have a basic privacy policy, a GDPR DPA template, and some internal Notion pages on our data handling. No formal AI policies yet.',
    dependsOn: { id: 'existingDocs', value: 'yes' },
    required: false,
  },
  {
    id: 'specificRequirements',
    label: 'Any specific requirements from investors or customers?',
    sub: 'Paste any exact wording from term sheets, RFPs, or procurement questionnaires. Optional but powerful.',
    type: 'textarea',
    placeholder: 'e.g. Our lead investor requires ISO 42001 certification within 12 months of Series A. Enterprise customer requires annual AI risk assessment signed by CEO.',
    required: false,
  },
]

// ── Helpers ─────────────────────────────────────────────────────
function safe(key) {
  try { return JSON.parse(localStorage.getItem(key) || 'null') } catch { return null }
}

function isStepComplete(q, answers) {
  if (!q.required) return true
  if (q.dependsOn && answers[q.dependsOn.id] !== q.dependsOn.value) return true
  const val = answers[q.id]
  if (!val) return false
  if (Array.isArray(val)) return val.length > 0
  return val.toString().trim().length > 0
}

// ── Context wizard ───────────────────────────────────────────────
function ContextWizard({ onComplete, company }) {
  const [step, setStep] = useState(0)
  const [answers, setAnswers] = useState({})

  const visibleQuestions = QUESTIONS.filter(q => {
    if (!q.dependsOn) return true
    return answers[q.dependsOn.id] === q.dependsOn.value
  })

  const q = visibleQuestions[step]
  const canProceed = q ? isStepComplete(q, answers) : true
  const isLast = step === visibleQuestions.length - 1

  const set = (id, val) => setAnswers(a => ({ ...a, [id]: val }))
  const toggle = (id, val) => setAnswers(a => ({
    ...a,
    [id]: (a[id] || []).includes(val) ? (a[id] || []).filter(v => v !== val) : [...(a[id] || []), val],
  }))

  const next = () => {
    if (isLast) { onComplete(answers); return }
    setStep(s => s + 1)
  }
  const back = () => setStep(s => Math.max(0, s - 1))

  const progress = Math.round(((step + 1) / visibleQuestions.length) * 100)

  return (
    <div style={{ maxWidth: 640, margin: '0 auto', padding: '56px 32px' }}>
      {/* Progress */}
      <div style={{ marginBottom: 40 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
          <span style={{ fontSize: 12, fontWeight: 600, color: '#059669' }}>Question {step + 1} of {visibleQuestions.length}</span>
          <span style={{ fontSize: 12, color: '#94A3B8' }}>{progress}% complete</span>
        </div>
        <div style={{ height: 4, background: '#F1F5F9', borderRadius: 2, overflow: 'hidden' }}>
          <div style={{ height: '100%', width: `${progress}%`, background: '#059669', borderRadius: 2, transition: 'width 300ms ease' }} />
        </div>
      </div>

      {/* Header */}
      <div style={{ marginBottom: 32 }}>
        <div className="eyebrow" style={{ marginBottom: 10 }}>Context intake — {company?.companyName}</div>
        <h2 style={{ fontSize: 'clamp(20px,2.8vw,28px)', fontWeight: 800, letterSpacing: '-0.03em', color: '#0F172A', marginBottom: 10 }}>{q?.label}</h2>
        <p style={{ fontSize: 14, color: '#475569', lineHeight: 1.65 }}>{q?.sub}</p>
      </div>

      {/* Input */}
      <div style={{ marginBottom: 32 }}>
        {q?.type === 'textarea' && (
          <textarea
            value={answers[q.id] || ''}
            onChange={e => set(q.id, e.target.value)}
            placeholder={q.placeholder}
            rows={5}
            autoFocus
            style={{ width: '100%', background: '#fff', border: '1px solid #CBD5E1', borderRadius: 8, color: '#0F172A', fontFamily: 'Inter, sans-serif', fontSize: 14, padding: '12px 14px', outline: 'none', resize: 'vertical', lineHeight: 1.6, transition: 'border-color 150ms, box-shadow 150ms' }}
            onFocus={e => { e.target.style.borderColor = '#059669'; e.target.style.boxShadow = '0 0 0 3px rgba(5,150,105,0.12)' }}
            onBlur={e => { e.target.style.borderColor = '#CBD5E1'; e.target.style.boxShadow = 'none' }}
          />
        )}

        {q?.type === 'multiselect' && (
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
            {q.options.map(opt => {
              const active = (answers[q.id] || []).includes(opt)
              return (
                <button key={opt} onClick={() => toggle(q.id, opt)}
                  style={{ padding: '9px 16px', border: `1.5px solid ${active ? '#059669' : '#E2E8F0'}`, borderRadius: 8, background: active ? '#ECFDF5' : '#fff', color: active ? '#047857' : '#475569', fontSize: 14, fontWeight: active ? 600 : 400, cursor: 'pointer', fontFamily: 'Inter, sans-serif', transition: 'all 150ms' }}>
                  {active && <span style={{ marginRight: 6 }}>✓</span>}{opt}
                </button>
              )
            })}
          </div>
        )}

        {q?.type === 'singleselect' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {q.options.map(opt => {
              const val = opt.value || opt
              const label = opt.label || opt
              const sub = opt.sub
              const active = answers[q.id] === val
              return (
                <button key={val} onClick={() => set(q.id, val)}
                  style={{ padding: '14px 18px', border: `1.5px solid ${active ? '#059669' : '#E2E8F0'}`, borderRadius: 10, background: active ? '#ECFDF5' : '#fff', textAlign: 'left', cursor: 'pointer', fontFamily: 'Inter, sans-serif', transition: 'all 150ms', display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                  <div style={{ width: 18, height: 18, borderRadius: '50%', border: `2px solid ${active ? '#059669' : '#CBD5E1'}`, background: active ? '#059669' : '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 1 }}>
                    {active && <div style={{ width: 6, height: 6, borderRadius: '50%', background: '#fff' }} />}
                  </div>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 600, color: '#0F172A' }}>{label}</div>
                    {sub && <div style={{ fontSize: 12, color: '#94A3B8', marginTop: 2 }}>{sub}</div>}
                  </div>
                </button>
              )
            })}
          </div>
        )}

        {q?.type === 'yesno' && (
          <div style={{ display: 'flex', gap: 12 }}>
            {[['yes', 'Yes, we have some'], ['no', 'No, starting from scratch']].map(([val, label]) => {
              const active = answers[q.id] === val
              return (
                <button key={val} onClick={() => set(q.id, val)}
                  style={{ flex: 1, padding: '16px', border: `1.5px solid ${active ? '#059669' : '#E2E8F0'}`, borderRadius: 10, background: active ? '#ECFDF5' : '#fff', fontSize: 14, fontWeight: active ? 600 : 400, color: active ? '#047857' : '#475569', cursor: 'pointer', fontFamily: 'Inter, sans-serif', transition: 'all 150ms', textAlign: 'center' }}>
                  {active && '✓ '}{label}
                </button>
              )
            })}
          </div>
        )}
      </div>

      {/* Navigation */}
      <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
        {step > 0 && (
          <button onClick={back} className="btn btn-secondary" style={{ minWidth: 80 }}>← Back</button>
        )}
        <button onClick={next} disabled={!canProceed} className="btn btn-primary"
          style={{ flex: 1, justifyContent: 'center', opacity: canProceed ? 1 : 0.4, cursor: canProceed ? 'pointer' : 'not-allowed' }}>
          {isLast ? 'Generate my policies →' : 'Continue →'}
        </button>
      </div>

      {!q?.required && (
        <button onClick={next} style={{ display: 'block', width: '100%', marginTop: 12, background: 'none', border: 'none', cursor: 'pointer', fontSize: 13, color: '#94A3B8', fontFamily: 'Inter, sans-serif' }}>
          Skip this question
        </button>
      )}
    </div>
  )
}

// ── Generate button ──────────────────────────────────────────────
function GenerateButton({ doc, company, results, context }) {
  const [status, setStatus] = useState('idle')
  const [errorMsg, setErrorMsg] = useState('')

  const generate = async () => {
    if (status === 'loading') return
    setStatus('loading')
    setErrorMsg('')
    try {
      const res = await fetch('/api/generate-policy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ policyId: doc.id, company, results, context }),
      })
      if (!res.ok) {
        const err = await res.json().catch(() => ({}))
        throw new Error(err.error || `Server error ${res.status}`)
      }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${doc.name.replace(/\s+/g, '_')}_v1.0.docx`
      document.body.appendChild(a); a.click(); document.body.removeChild(a)
      URL.revokeObjectURL(url)
      setStatus('done')
    } catch (err) {
      setErrorMsg(err.message)
      setStatus('error')
    }
  }

  const base = { display: 'inline-flex', alignItems: 'center', gap: 8, padding: '7px 14px', borderRadius: 6, fontSize: 13, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap', minWidth: 140, justifyContent: 'center', transition: 'all 150ms', border: 'none' }

  if (status === 'loading') return (
    <button disabled style={{ ...base, background: '#F0FDF4', border: '1px solid #A7F3D0', color: '#059669', cursor: 'not-allowed' }}>
      <div style={{ width: 13, height: 13, border: '2px solid #A7F3D0', borderTopColor: '#059669', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />
      Generating…
    </button>
  )

  if (status === 'done') return (
    <button onClick={generate} style={{ ...base, background: '#F0FDF4', border: '1px solid #059669', color: '#059669' }}>
      ✓ Download again
    </button>
  )

  if (status === 'error') return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
      <button onClick={generate} style={{ ...base, background: '#FEF2F2', border: '1px solid #FCA5A5', color: '#DC2626' }}>Retry ↺</button>
      <span style={{ fontSize: 11, color: '#DC2626', maxWidth: 180, textAlign: 'right' }}>{errorMsg}</span>
    </div>
  )

  return (
    <button onClick={generate} style={{ ...base, background: '#fff', border: '1px solid #CBD5E1', color: '#0F172A' }}>
      ↓ Generate .docx
    </button>
  )
}

// ── Download section (shown after payment + context intake) ──────
function DownloadSection({ company, results, context, onEditContext }) {
  return (
    <div style={{ maxWidth: 820, margin: '0 auto', padding: '48px 40px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 36, flexWrap: 'wrap', gap: 16 }}>
        <div>
          <div className="eyebrow" style={{ marginBottom: 10 }}>Policy Pack — {company?.companyName}</div>
          <h1 style={{ fontSize: 'clamp(22px,3vw,30px)', fontWeight: 800, letterSpacing: '-0.03em', color: '#0F172A', marginBottom: 8 }}>Generate your 7 policy documents</h1>
          <p style={{ fontSize: 14, color: '#475569', maxWidth: 500 }}>Each document is generated on-demand by Claude AI using your assessment answers and intake context. Click Generate on each one — download starts automatically.</p>
        </div>
        <button onClick={onEditContext} className="btn btn-secondary btn-sm">Edit intake answers</button>
      </div>

      {/* Context summary */}
      {context && (
        <div className="card" style={{ padding: '16px 20px', marginBottom: 20, background: '#F8FAFC' }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: '#94A3B8', letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 10 }}>Context used for generation</div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px 24px' }}>
            {context.aiDescription && <div style={{ fontSize: 13, color: '#475569' }}><strong style={{ color: '#0F172A' }}>AI use case:</strong> {context.aiDescription.slice(0, 80)}{context.aiDescription.length > 80 ? '…' : ''}</div>}
            {context.jurisdictions?.length > 0 && <div style={{ fontSize: 13, color: '#475569' }}><strong style={{ color: '#0F172A' }}>Jurisdictions:</strong> {context.jurisdictions.join(', ')}</div>}
            {context.reviewers?.length > 0 && <div style={{ fontSize: 13, color: '#475569' }}><strong style={{ color: '#0F172A' }}>Reviewers:</strong> {context.reviewers.slice(0, 2).join(', ')}{context.reviewers.length > 2 ? ` +${context.reviewers.length - 2}` : ''}</div>}
            {context.personalData && <div style={{ fontSize: 13, color: '#475569' }}><strong style={{ color: '#0F172A' }}>Personal data:</strong> {context.personalData}</div>}
          </div>
        </div>
      )}

      {(!company || !results) && (
        <div style={{ padding: '14px 18px', background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: 8, marginBottom: 20, fontSize: 14, color: '#92400E' }}>
          No assessment data found. <Link to="/assessment" style={{ color: '#D97706', fontWeight: 600 }}>Complete the assessment first</Link> to personalise your documents.
        </div>
      )}

      <div className="card">
        <div style={{ padding: '14px 20px', borderBottom: '1px solid #E2E8F0', background: '#F8FAFC', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: 13, fontWeight: 700, color: '#0F172A' }}>7 policy documents</span>
          <span className="badge badge-green">Claude AI · Senior AI governance counsel</span>
        </div>
        {POLICY_DOCS.map((doc, i) => (
          <div key={doc.id} style={{ padding: '16px 20px', borderBottom: i < POLICY_DOCS.length - 1 ? '1px solid #F8FAFC' : 'none', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: '#0F172A', marginBottom: 2 }}>{doc.name}</div>
              <div className="mono" style={{ fontSize: 10, color: '#059669', fontWeight: 600 }}>{doc.clause}</div>
            </div>
            <GenerateButton doc={doc} company={company} results={results} context={context} />
          </div>
        ))}
      </div>
      <p style={{ fontSize: 12, color: '#94A3B8', textAlign: 'center', marginTop: 16 }}>Generation takes 30–60s per document · Word .docx · Re-generate any time</p>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}

// ── Payment form ─────────────────────────────────────────────────
function PaymentForm({ company, onPaid }) {
  const [selected, setSelected] = useState('pack')
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({ name: '', email: company?.email || '', card: '', expiry: '', cvc: '' })
  const [error, setError] = useState('')
  const plan = PLANS.find(p => p.id === selected)
  const formOk = form.name && form.email && form.card.length >= 16 && form.expiry && form.cvc

  const handlePay = async e => {
    e.preventDefault()
    setError('')
    if (!formOk) { setError('Please fill in all payment details.'); return }
    setLoading(true)
    await new Promise(r => setTimeout(r, 1800))
    try { localStorage.setItem('complai_paid', '1') } catch {}
    setLoading(false)
    onPaid()
  }

  return (
    <div style={{ maxWidth: 960, margin: '0 auto', padding: '48px 40px', display: 'grid', gridTemplateColumns: '1fr 360px', gap: 32, alignItems: 'flex-start' }}>
      <div>
        <div style={{ marginBottom: 32 }}>
          <div className="eyebrow" style={{ marginBottom: 12 }}>Policy Pack</div>
          <h1 style={{ fontSize: 'clamp(24px,3vw,38px)', fontWeight: 800, letterSpacing: '-0.04em', color: '#0F172A', marginBottom: 12 }}>Investor-ready AI governance policies</h1>
          <p style={{ fontSize: 15, color: '#475569', lineHeight: 1.65 }}>Generated by Claude AI with a senior AI governance counsel persona. Tailored to your company's specific gaps and context.</p>
        </div>
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#374151', marginBottom: 12 }}>Select a plan</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {PLANS.map(p => (
              <button key={p.id} onClick={() => setSelected(p.id)}
                style={{ background: selected === p.id ? '#ECFDF5' : '#fff', border: selected === p.id ? '2px solid #059669' : '1px solid #E2E8F0', borderRadius: 10, padding: '16px 20px', cursor: 'pointer', textAlign: 'left', display: 'flex', justifyContent: 'space-between', alignItems: 'center', transition: 'all 150ms', fontFamily: 'Inter, sans-serif' }}>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
                    <span style={{ fontSize: 14, fontWeight: 700, color: '#0F172A' }}>{p.label}</span>
                    {p.popular && <span className="badge badge-green" style={{ fontSize: 10 }}>Most popular</span>}
                  </div>
                  <div style={{ fontSize: 13, color: '#64748B' }}>{p.desc}</div>
                </div>
                <div style={{ textAlign: 'right', flexShrink: 0, marginLeft: 16 }}>
                  <div className="mono" style={{ fontSize: 22, fontWeight: 800, color: '#0F172A' }}>{p.price}</div>
                  <div style={{ fontSize: 11, color: '#94A3B8' }}>{p.period}</div>
                </div>
              </button>
            ))}
          </div>
        </div>
        <div className="card">
          <div style={{ padding: '14px 20px', borderBottom: '1px solid #E2E8F0', background: '#F8FAFC' }}>
            <span style={{ fontSize: 13, fontWeight: 700, color: '#0F172A' }}>What you'll receive</span>
          </div>
          {POLICY_DOCS.map((doc, i) => (
            <div key={doc.id} style={{ padding: '11px 20px', borderBottom: i < POLICY_DOCS.length - 1 ? '1px solid #F8FAFC' : 'none', display: 'flex', gap: 10 }}>
              <span style={{ color: '#059669', fontWeight: 700, fontSize: 13, flexShrink: 0 }}>✓</span>
              <span style={{ fontSize: 13, color: '#374151' }}>{doc.name}</span>
            </div>
          ))}
        </div>
        <div className="card" style={{ marginTop: 14, padding: '14px 20px', background: '#F0FDF4', border: '1px solid #A7F3D0' }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: '#047857', marginBottom: 4 }}>30-day money-back guarantee</div>
          <div style={{ fontSize: 13, color: '#065F46' }}>If your documents don't pass investor or procurement review, refund in full — no questions asked.</div>
        </div>
      </div>

      <div className="card" style={{ padding: '28px 24px' }}>
        <div style={{ fontSize: 14, fontWeight: 700, color: '#0F172A', marginBottom: 4 }}>Complete your order</div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', background: '#F8FAFC', borderRadius: 8, border: '1px solid #E2E8F0', marginTop: 12, marginBottom: 20 }}>
          <span style={{ fontSize: 13, color: '#475569' }}>{plan.label}</span>
          <span className="mono" style={{ fontSize: 16, fontWeight: 800, color: '#0F172A' }}>{plan.price}</span>
        </div>
        <form onSubmit={handlePay}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {[['name','Full name','text','Jane Smith'],['email','Email','email','jane@company.com']].map(([id,label,type,ph]) => (
              <div key={id} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>{label}</label>
                <input className="inp" type={type} placeholder={ph} value={form[id]} onChange={e => setForm(f => ({ ...f, [id]: e.target.value }))} />
              </div>
            ))}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>Card number</label>
              <input className="inp" placeholder="1234 5678 9012 3456" value={form.card} onChange={e => setForm(f => ({ ...f, card: e.target.value.replace(/\D/g,'').slice(0,16) }))} />
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>Expiry</label>
                <input className="inp" placeholder="MM / YY" value={form.expiry} onChange={e => setForm(f => ({ ...f, expiry: e.target.value }))} />
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>CVC</label>
                <input className="inp" placeholder="123" value={form.cvc} onChange={e => setForm(f => ({ ...f, cvc: e.target.value.slice(0,4) }))} />
              </div>
            </div>
            {error && <div style={{ padding: '10px 14px', background: '#FEF2F2', border: '1px solid #FCA5A5', borderRadius: 8, fontSize: 13, color: '#DC2626' }}>{error}</div>}
            <button type="submit" disabled={!formOk || loading} className="btn btn-primary btn-lg"
              style={{ justifyContent: 'center', marginTop: 4, opacity: formOk && !loading ? 1 : 0.45, cursor: formOk && !loading ? 'pointer' : 'not-allowed' }}>
              {loading ? <><div style={{ width: 14, height: 14, border: '2px solid rgba(255,255,255,0.3)', borderTopColor: '#fff', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} /> Processing…</> : `Pay ${plan.price} →`}
            </button>
            <p style={{ fontSize: 11, color: '#94A3B8', textAlign: 'center' }}>Secured by Stripe · SSL encrypted · 30-day guarantee</p>
          </div>
        </form>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}

// ── Main page ────────────────────────────────────────────────────
export default function Policies() {
  const [stage, setStage] = useState('loading') // loading | pay | intake | generate
  const [company, setCompany] = useState(null)
  const [results, setResults] = useState(null)
  const [context, setContext] = useState(null)

  useEffect(() => {
    const c = safe('complai_company')
    const r = safe('complai_results')
    const ctx = safe('complai_context')
    const paid = localStorage.getItem('complai_paid')
    if (c) setCompany(c)
    if (r) setResults(r)
    if (ctx) setContext(ctx)
    if (paid && ctx) setStage('generate')
    else if (paid && !ctx) setStage('intake')
    else setStage('pay')
  }, [])

  const handlePaid = () => setStage('intake')

  const handleContext = answers => {
    try { localStorage.setItem('complai_context', JSON.stringify(answers)) } catch {}
    setContext(answers)
    setStage('generate')
  }

  const handleEditContext = () => setStage('intake')

  if (stage === 'loading') return (
    <div style={{ background: '#F8FAFC', minHeight: '100dvh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: 28, height: 28, border: '2px solid #E2E8F0', borderTopColor: '#059669', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )

  return (
    <div style={{ background: '#F8FAFC', minHeight: '100dvh' }}>
      <nav className="nav">
        <Link to="/" style={{ fontWeight: 800, fontSize: 15, letterSpacing: '-0.04em', color: '#0F172A', textDecoration: 'none', marginRight: 'auto' }}>COMPLAI</Link>
        {stage !== 'pay' && <Link to="/results" className="nav-link" style={{ marginRight: 8 }}>View results</Link>}
        {stage === 'generate' && <button onClick={handleEditContext} className="btn btn-secondary btn-sm">Edit context</button>}
      </nav>

      {stage === 'pay'      && <PaymentForm company={company} onPaid={handlePaid} />}
      {stage === 'intake'   && <ContextWizard onComplete={handleContext} company={company} />}
      {stage === 'generate' && <DownloadSection company={company} results={results} context={context} onEditContext={handleEditContext} />}
    </div>
  )
}
