import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'

const PLANS = [
  { id: 'pack', label: 'Policy Pack', price: '$299', period: 'one-time', desc: '7 AI governance documents, generated by Claude AI, customised to your company', popular: true },
  { id: 'annual', label: 'Annual', price: '$199', period: '/ year', desc: 'Policy pack + annual refresh + new templates as standards evolve' },
]

const POLICY_DOCS = [
  { id: 'ai-governance',   name: 'AI Governance Policy',                   clause: 'ISO 42001 §4–6',          desc: 'Master governance framework and AI principles' },
  { id: 'risk-framework',  name: 'AI Risk Assessment Framework',            clause: 'ISO 42001 §6.1, 8.4',     desc: 'Risk scoring methodology, heat maps, treatment options' },
  { id: 'incident-response', name: 'AI Incident Response Plan',            clause: 'ISO 42001 §8.3, 10.1',    desc: 'Severity playbooks, SLAs, regulator notification timelines' },
  { id: 'transparency',    name: 'Transparency & Explainability Policy',    clause: 'ISO 42001 §8.5; EU AI Act Art.13', desc: 'Disclosure obligations, explainability standards, user rights' },
  { id: 'data-governance', name: 'AI Data Governance Policy',              clause: 'ISO 42001 §8.2, 8.6; GDPR Art.35', desc: 'Training data quality, bias mitigation, DPIA requirements' },
  { id: 'vendor-policy',   name: 'Third-Party AI Vendor Policy',           clause: 'ISO 42001 §8.7; GDPR Art.28', desc: 'Vendor due diligence, DPA requirements, exit procedures' },
  { id: 'readiness-report', name: 'ISO 42001 Readiness Report',            clause: 'ISO 42001 — Full Standard', desc: 'Executive gap analysis and remediation roadmap for investors' },
]

function safe(key) {
  try { return JSON.parse(localStorage.getItem(key) || 'null') } catch { return null }
}

function GenerateButton({ doc, company, results, disabled }) {
  const [status, setStatus] = useState('idle') // idle | loading | done | error
  const [errorMsg, setErrorMsg] = useState('')

  const generate = async () => {
    if (disabled || status === 'loading') return
    setStatus('loading')
    setErrorMsg('')
    try {
      const res = await fetch('/api/generate-policy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ policyId: doc.id, company, results }),
      })
      if (!res.ok) {
        const err = await res.json().catch(() => ({}))
        throw new Error(err.error || `Server error ${res.status}`)
      }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${doc.name.replace(/\s+/g, '_')}_v1.0.docx`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      setStatus('done')
    } catch (err) {
      setErrorMsg(err.message)
      setStatus('error')
    }
  }

  if (status === 'loading') return (
    <button disabled style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '7px 14px', background: '#F0FDF4', border: '1px solid #A7F3D0', borderRadius: 6, fontSize: 13, fontWeight: 600, color: '#059669', cursor: 'not-allowed', whiteSpace: 'nowrap', minWidth: 160 }}>
      <div style={{ width: 13, height: 13, border: '2px solid #A7F3D0', borderTopColor: '#059669', borderRadius: '50%', animation: 'spin 0.7s linear infinite', flexShrink: 0 }} />
      Generating…
    </button>
  )

  if (status === 'done') return (
    <button onClick={generate} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '7px 14px', background: '#F0FDF4', border: '1px solid #059669', borderRadius: 6, fontSize: 13, fontWeight: 600, color: '#059669', cursor: 'pointer', whiteSpace: 'nowrap' }}>
      ✓ Download again
    </button>
  )

  if (status === 'error') return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 }}>
      <button onClick={generate} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '7px 14px', background: '#FEF2F2', border: '1px solid #FCA5A5', borderRadius: 6, fontSize: 13, fontWeight: 600, color: '#DC2626', cursor: 'pointer', whiteSpace: 'nowrap' }}>
        Retry ↺
      </button>
      <span style={{ fontSize: 11, color: '#DC2626', maxWidth: 180, textAlign: 'right' }}>{errorMsg}</span>
    </div>
  )

  return (
    <button onClick={generate} disabled={disabled}
      style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '7px 14px', background: disabled ? '#F8FAFC' : '#fff', border: `1px solid ${disabled ? '#E2E8F0' : '#CBD5E1'}`, borderRadius: 6, fontSize: 13, fontWeight: 600, color: disabled ? '#CBD5E1' : '#0F172A', cursor: disabled ? 'not-allowed' : 'pointer', whiteSpace: 'nowrap', transition: 'all 150ms' }}>
      ↓ Generate
    </button>
  )
}

function DownloadSection({ company, results }) {
  return (
    <div style={{ maxWidth: 780, margin: '0 auto', padding: '56px 40px' }}>
      <div style={{ marginBottom: 40 }}>
        <div style={{ width: 52, height: 52, background: '#ECFDF5', border: '1px solid #A7F3D0', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 20, fontSize: 22, color: '#059669', fontWeight: 700 }}>✓</div>
        <div className="eyebrow" style={{ marginBottom: 10 }}>Payment confirmed</div>
        <h1 style={{ fontSize: 'clamp(22px,3vw,32px)', fontWeight: 800, letterSpacing: '-0.03em', color: '#0F172A', marginBottom: 10 }}>Your policies are ready to generate</h1>
        <p style={{ fontSize: 15, color: '#475569', lineHeight: 1.65 }}>
          Each document is generated on-demand by Claude AI using your assessment answers. They are fully customised for <strong>{company?.companyName}</strong> and reference your specific gaps.
        </p>
      </div>

      {(!company || !results) && (
        <div style={{ padding: '16px 20px', background: '#FFFBEB', border: '1px solid #FDE68A', borderRadius: 8, marginBottom: 24, fontSize: 14, color: '#92400E' }}>
          No assessment data found. <Link to="/assessment" style={{ color: '#D97706', fontWeight: 600 }}>Complete the assessment first</Link> to personalise your documents.
        </div>
      )}

      <div className="card">
        <div style={{ padding: '14px 20px', borderBottom: '1px solid #E2E8F0', background: '#F8FAFC', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ fontSize: 13, fontWeight: 700, color: '#0F172A' }}>7 policy documents</span>
          <span className="badge badge-green">Claude AI · ISO 42001 expert</span>
        </div>

        {POLICY_DOCS.map((doc, i) => (
          <div key={doc.id} style={{ padding: '16px 20px', borderBottom: i < POLICY_DOCS.length - 1 ? '1px solid #F8FAFC' : 'none', display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontSize: 14, fontWeight: 600, color: '#0F172A', marginBottom: 3 }}>{doc.name}</div>
              <div style={{ fontSize: 12, color: '#94A3B8', marginBottom: 2 }}>{doc.desc}</div>
              <div className="mono" style={{ fontSize: 10, color: '#059669', fontWeight: 600 }}>{doc.clause}</div>
            </div>
            <GenerateButton doc={doc} company={company} results={results} disabled={!company || !results} />
          </div>
        ))}
      </div>

      <p style={{ fontSize: 12, color: '#94A3B8', textAlign: 'center', marginTop: 20 }}>
        Generation takes 30–60 seconds per document · Word .docx format · Re-generate any time
      </p>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}

export default function Policies() {
  const [selected, setSelected] = useState('pack')
  const [loading, setLoading] = useState(false)
  const [paid, setPaid] = useState(false)
  const [form, setForm] = useState({ name: '', email: '', card: '', expiry: '', cvc: '' })
  const [error, setError] = useState('')
  const [company, setCompany] = useState(null)
  const [results, setResults] = useState(null)

  useEffect(() => {
    const c = safe('complai_company')
    const r = safe('complai_results')
    const p = localStorage.getItem('complai_paid')
    if (c) { setCompany(c); setForm(f => ({ ...f, email: c.email || '' })) }
    if (r) setResults(r)
    if (p) setPaid(true)
  }, [])

  const plan = PLANS.find(p => p.id === selected)
  const formOk = form.name && form.email && form.card.length >= 16 && form.expiry && form.cvc

  const handlePay = async e => {
    e.preventDefault()
    setError('')
    if (!formOk) { setError('Please fill in all payment details.'); return }
    setLoading(true)
    await new Promise(r => setTimeout(r, 1800))
    try { localStorage.setItem('complai_paid', '1') } catch {}
    setPaid(true)
    setLoading(false)
  }

  if (paid) return (
    <div style={{ background: '#F8FAFC', minHeight: '100dvh' }}>
      <nav className="nav">
        <Link to="/" style={{ fontWeight: 800, fontSize: 15, letterSpacing: '-0.04em', color: '#0F172A', textDecoration: 'none', marginRight: 'auto' }}>COMPLAI</Link>
        <Link to="/results" className="btn btn-secondary btn-sm">View results</Link>
      </nav>
      <DownloadSection company={company} results={results} />
    </div>
  )

  return (
    <div style={{ background: '#F8FAFC', minHeight: '100dvh' }}>
      <nav className="nav">
        <Link to="/" style={{ fontWeight: 800, fontSize: 15, letterSpacing: '-0.04em', color: '#0F172A', textDecoration: 'none', marginRight: 'auto' }}>COMPLAI</Link>
        <Link to="/results" className="nav-link">View results</Link>
      </nav>

      <div style={{ maxWidth: 960, margin: '0 auto', padding: '48px 40px', display: 'grid', gridTemplateColumns: '1fr 360px', gap: 32, alignItems: 'flex-start' }}>
        <div>
          <div style={{ marginBottom: 32 }}>
            <div className="eyebrow" style={{ marginBottom: 12 }}>Policy Pack</div>
            <h1 style={{ fontSize: 'clamp(24px,3vw,38px)', fontWeight: 800, letterSpacing: '-0.04em', color: '#0F172A', marginBottom: 12 }}>Investor-ready AI governance policies</h1>
            <p style={{ fontSize: 15, color: '#475569', lineHeight: 1.65, maxWidth: 520 }}>
              Generated by Claude AI with a senior AI governance counsel persona. Each document references specific ISO 42001 clauses, EU AI Act articles, and GDPR obligations — tailored to your company's gaps.
            </p>
          </div>

          <div style={{ marginBottom: 24 }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: '#374151', marginBottom: 12 }}>Select a plan</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {PLANS.map(p => (
                <button key={p.id} onClick={() => setSelected(p.id)}
                  style={{ background: selected === p.id ? '#ECFDF5' : '#fff', border: selected === p.id ? '2px solid #059669' : '1px solid #E2E8F0', borderRadius: 10, padding: '16px 20px', cursor: 'pointer', textAlign: 'left', display: 'flex', justifyContent: 'space-between', alignItems: 'center', transition: 'all 150ms', fontFamily: 'Inter, sans-serif' }}>
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
                      <span style={{ fontSize: 14, fontWeight: 700, color: '#0F172A' }}>{p.label}</span>
                      {p.popular && <span className="badge badge-green" style={{ fontSize: 10 }}>Most popular</span>}
                    </div>
                    <div style={{ fontSize: 13, color: '#64748B' }}>{p.desc}</div>
                  </div>
                  <div style={{ textAlign: 'right', flexShrink: 0, marginLeft: 16 }}>
                    <div className="mono" style={{ fontSize: 22, fontWeight: 800, color: '#0F172A' }}>{p.price}</div>
                    <div style={{ fontSize: 11, color: '#94A3B8' }}>{p.period}</div>
                  </div>
                </button>
              ))}
            </div>
          </div>

          <div className="card">
            <div style={{ padding: '14px 20px', borderBottom: '1px solid #E2E8F0', background: '#F8FAFC' }}>
              <span style={{ fontSize: 13, fontWeight: 700, color: '#0F172A' }}>What you'll receive</span>
            </div>
            {POLICY_DOCS.map((doc, i) => (
              <div key={doc.id} style={{ padding: '12px 20px', borderBottom: i < POLICY_DOCS.length - 1 ? '1px solid #F8FAFC' : 'none', display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                <span style={{ color: '#059669', fontWeight: 700, fontSize: 13, flexShrink: 0, paddingTop: 1 }}>✓</span>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>{doc.name}</div>
                  <div style={{ fontSize: 12, color: '#94A3B8' }}>{doc.desc}</div>
                </div>
              </div>
            ))}
          </div>

          <div className="card" style={{ marginTop: 16, padding: '16px 20px', background: '#F0FDF4', border: '1px solid #A7F3D0' }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: '#047857', marginBottom: 4 }}>30-day money-back guarantee</div>
            <div style={{ fontSize: 13, color: '#065F46' }}>If your documents don't pass investor or enterprise procurement review, we'll refund you in full — no questions asked.</div>
          </div>
        </div>

        <div className="card" style={{ padding: '28px 24px' }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: '#0F172A', marginBottom: 4 }}>Complete your order</div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 16px', background: '#F8FAFC', borderRadius: 8, border: '1px solid #E2E8F0', marginTop: 12, marginBottom: 20 }}>
            <span style={{ fontSize: 13, color: '#475569' }}>{plan.label}</span>
            <span className="mono" style={{ fontSize: 16, fontWeight: 800, color: '#0F172A' }}>{plan.price}</span>
          </div>

          <form onSubmit={handlePay}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>Full name</label>
                <input className="inp" placeholder="Jane Smith" value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} />
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>Email</label>
                <input className="inp" type="email" placeholder="jane@company.com" value={form.email} onChange={e => setForm(f => ({ ...f, email: e.target.value }))} />
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>Card number</label>
                <input className="inp" placeholder="1234 5678 9012 3456" value={form.card} onChange={e => setForm(f => ({ ...f, card: e.target.value.replace(/\D/g, '').slice(0, 16) }))} />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>Expiry</label>
                  <input className="inp" placeholder="MM / YY" value={form.expiry} onChange={e => setForm(f => ({ ...f, expiry: e.target.value }))} />
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                  <label style={{ fontSize: 13, fontWeight: 600, color: '#374151' }}>CVC</label>
                  <input className="inp" placeholder="123" value={form.cvc} onChange={e => setForm(f => ({ ...f, cvc: e.target.value.slice(0, 4) }))} />
                </div>
              </div>
              {error && <div style={{ padding: '10px 14px', background: '#FEF2F2', border: '1px solid #FCA5A5', borderRadius: 8, fontSize: 13, color: '#DC2626' }}>{error}</div>}
              <button type="submit" disabled={!formOk || loading} className="btn btn-primary btn-lg"
                style={{ justifyContent: 'center', marginTop: 4, opacity: formOk && !loading ? 1 : 0.45, cursor: formOk && !loading ? 'pointer' : 'not-allowed' }}>
                {loading
                  ? <><div style={{ width: 14, height: 14, border: '2px solid rgba(255,255,255,0.3)', borderTopColor: '#fff', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} /> Processing…</>
                  : `Pay ${plan.price} →`}
              </button>
              <p style={{ fontSize: 11, color: '#94A3B8', textAlign: 'center' }}>Secured by Stripe · SSL encrypted · 30-day guarantee</p>
            </div>
          </form>
        </div>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}
